### ISSUE TITLE
When running "example0_1_orbits": " AttributeError: module 'pynauty' has no attribute 'Graph' ". Is this expected?

### ISSUE THREAD

**Issue by makansij** [dwavesystems/shimming-tutorial#8]
Hello, 

I'm trying to run the examples from the shimming tutorial found here: https://github.com/dwavesystems/shimming-tutorial/tree/main  

All of the installations in `requirements.txt` run fine, but the examples do not.  

When I run the first example like so: 

``` 

python -m example0_1_orbits 

``` 

I'm faced with the following error: " AttributeError: module 'pynauty' has no attribute 'Graph' ".   

Can someone please confirm that this is a legitimate bug?   

For what it's worth, I also tried the most recent version of pynauty (version 2.8.8).  This doesn't seem to change anything.

I'm using Python3.10 as suggested, and no other warnings/errors occur. 

Thanks.

**Comment by makansij** [comment]
This has also been posted here: https://support.dwavesys.com/hc/en-us/community/posts/30949420242839-Is-this-a-bug-in-the-tutorial wthout resolution.

**Comment by kevinchern** [comment]
Hi Jordan, thanks for flagging this. This should be fixed from https://github.com/dwavesystems/shimming-tutorial/pull/7.

**Comment by makansij** [comment]
@kevinchern Thanks for your response to this.  I cloned the repo again, but I'm still having the same issue.  What do I need to do differently?  Thank you.

**Comment by kevinchern** [comment]
👀👀 @makansij could you provide a script to reproduce the error (along with a pip freeze)? whats your operating system?

**Comment by makansij** [comment]
Certainly:

- OS:  MacOS Sequoia 15.3.2 (24D81)
- pip freeze is attached as pip_freeze.txt
To reproduce, run the code below in a shell script from the root directory:
```
pip install -r requirements.txt
pip freeze > pip_freeze.txt
cd tutorial_code
python -m example0_1_orbits
~                                   
```
[pip_freeze.txt](https://github.com/user-attachments/files/19910259/pip_freeze.txt)

**Comment by kevinchern** [comment]
Looks like there are many additional packages installed. Could you try reproducing this in a virtual environment? e.g., [miniforge](https://github.com/conda-forge/miniforge) or [venv](https://docs.python.org/3/library/venv.html)
